function S = requireStage(file, stageName, howToFix)
%REQUIRESTAGE  Load a pipeline artefact, or explain exactly what to run first.
if ~isfile(file)
    [~,n,e] = fileparts(file);
    error('NETRA:missingStage', ...
        ['\n  Missing: %s%s\n' ...
         '  This comes from: %s\n' ...
         '  Do this first:   %s\n' ...
         '  Or just run:     run_all\n'], n, e, stageName, howToFix);
end
S = load(file);
end
