%S26_GOLDEN_REFS  MATLAB ground truth for the Python port's parity tests.
%
%   Runs netraAnalyze on a small, varied set of REAL images and saves every
%   intermediate the Python side recomputes, to web/tests/golden/*.mat (-v7,
%   readable by scipy). After the MATLAB licence lapses these files are the
%   only way to prove the web app still computes what was measured here.
%
%     2 IDRiD test images   native 4288x2848, the lesion net's home domain
%     2 DRIVE test images   584x565, the vessel net's home domain
%     5 APTOS images        one per ICDR grade, from the EfficientNet's own
%                           held-out split (s27), mixed camera sizes
%     1 degraded capture    IDRiD_61 blurred + darkened: exercises REJECT
%
%   The golden set is large (full-resolution probability maps) and is
%   regenerated by this script, so it is not committed.
here = fileparts(mfilename('fullpath'));
addpath(here, fullfile(here,'lib'), fullfile(here,'m1_quality'));
CFG = s00_config();
out = fullfile(CFG.root,'web','tests','golden');
if ~isfolder(out), mkdir(out); end

idr = fullfile(CFG.segRoot,'1. Original Images','b. Testing Set');
items = {fullfile(idr,'IDRiD_55.jpg'), fullfile(idr,'IDRiD_63.jpg'), ...
         fullfile(CFG.driveRoot,'val','input','01.tif'), fullfile(CFG.driveRoot,'val','input','04.tif')};

T = readtable(fullfile(CFG.resultDir,'effnet_dual_evidence.csv'), 'TextType','string');
for g = 0:4
    k = find(T.Truth == g, 1);
    items{end+1} = fullfile(CFG.aptosImgDir, T.Image(k) + ".png"); %#ok<SAGROW>
end

% degraded capture: a real photo made ungradeable (blur + underexposure)
bad = imread(fullfile(idr,'IDRiD_61.jpg'));
bad = uint8(0.35 * double(imgaussfilt(bad, 25)));
badPath = fullfile(out,'degraded_IDRiD_61.png');
imwrite(bad, badPath);
items{end+1} = badPath;

for i = 1:numel(items)
    p = char(items{i});
    [~, nm] = fileparts(p);
    Iraw = imread(p);
    if size(Iraw,3) == 1, Iraw = repmat(Iraw,1,1,3); end
    S = netraAnalyze(Iraw);

    G = struct();
    G.path = p; G.raw = Iraw; G.bbox = S.bbox; G.crop = S.image;
    [G.retina, G.retinaFrac, G.retinaClipped] = retinalMask(S.image);
    G.qDecision = char(S.quality.decision); G.qScore = S.quality.score;
    G.qMetrics = S.quality.metrics;
    G.graderInput = imresize(Iraw,[160 160]);
    % pure image-processing checks that need no network
    G.claheOnCrop = applyClahe(S.image);
    g = im2single(S.image(:,:,2));
    G.resize1024 = imresize(g, 1024/size(g,2));
    if S.decisionPath ~= "REJECTED_AT_QUALITY_GATE"
        G.lesionProb = S.lesions.prob;  G.lesionMasks = S.lesions.masks;
        G.counts = [S.ruleGrade.counts.MA S.ruleGrade.counts.HE S.ruleGrade.counts.EX S.ruleGrade.counts.SE];
        G.ruleGrade = S.ruleGrade.grade; G.quadrantHaem = S.ruleGrade.quadrantHaem;
        G.vesselProb = S.vessels.prob; G.vesselMask = S.vessels.mask; G.vesselScale = S.vessels.scale;
        G.graderProb = S.grader.prob;  G.graderCam = S.grader.cam;
        G.dual = char(S.dual.decision); G.finalGrade = S.finalGrade; G.referable = S.referable;
    end
    G.decisionPath = char(S.decisionPath); G.reportLine = char(S.reportLine);
    save(fullfile(out, [nm '.mat']), '-struct', 'G', '-v7');
    fprintf('%-28s %-10s %s\n', nm, S.quality.decision, S.reportLine);
end
