"""Build web/models/metrics.json from the measured results - nothing typed by hand.

    python web/tools/build_metrics.py

Reads results/deck_facts.txt (written by s12/s14/s16/s21/s30). A fact missing
there is simply not shown; the web app never displays a number no script measured.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
facts = {}
for line in (ROOT / 'results' / 'deck_facts.txt').read_text(encoding='utf-8').splitlines():
    m = re.match(r'\s*([\w.]+)\s*=\s*([-\d.\s]+?)\s*(#.*)?$', line)
    if m:
        vals = [float(v) for v in m.group(2).split()]
        facts[m.group(1)] = vals if len(vals) > 1 else vals[0]


def pct(v):
    return f'{100 * v:.1f}%'


def num(v):
    return f'{v:.3f}'


def get(key, idx=None):
    v = facts[key]
    return v[idx] if idx is not None else v


LV = 'lesion_v2'
SPEC = [
    ('Model 1 - ResNet-18 grader', 'Referable DR sensitivity / specificity',
     lambda: f"{pct(get('grader.sensitivity'))} / {pct(get('grader.specificity'))}",
     'sealed APTOS test split, n=549 (s12)'),
    ('Model 1 - ResNet-18 grader', 'Referable DR ROC AUC', lambda: num(get('grader.roc_auc')),
     'sealed APTOS test split, n=549 (s12)'),
    ('Model 1 - ResNet-18 grader', '5-class quadratic kappa', lambda: num(get('grader.qwk')),
     'sealed APTOS test split, n=549 (s12)'),
    ('Model 1 - lesion net (v2)', 'Dice: hard exudate / haemorrhage / soft exudate / MA',
     lambda: ' / '.join(num(get(f'{LV}.idrid_dice', i)) for i in (2, 1, 3, 0)),
     'IDRiD official test, 27 images (all with DR)'),
    ('Model 1 - lesion net (v2)', 'Healthy eyes called referable by the lesion rules',
     lambda: f"{pct(get(f'{LV}.healthy_false_referral'))} (was {pct(get('lesion_v1.healthy_false_referral'))} before retraining)",
     'sealed APTOS test split, 270 healthy eyes (s30)'),
    ('Model 2 - vessel net', 'Dice / sensitivity / specificity',
     lambda: f"{num(get('vessel.dice'))} / {pct(get('vessel.sensitivity'))} / {pct(get('vessel.specificity'))}",
     'DRIVE official test, 20 images'),
    ('Dual-evidence check', 'Cases escalated to an ophthalmologist',
     lambda: pct(get(f'{LV}.d2_escalation_rate')), 'sealed APTOS test split, n=549 (s30)'),
    ('Dual-evidence check', 'Grader referral errors caught', lambda: pct(get(f'{LV}.d2_grader_errors_caught')),
     'sealed APTOS test split, n=549 (s30)'),
    ('Dual-evidence check', 'Referable eyes the grader missed that were auto-cleared',
     lambda: f"{get(f'{LV}.d2_silent_misses'):.0f}", 'sealed APTOS test split, n=549 (s30)'),
]

rows = []
for model, metric, fmt, test_set in SPEC:
    try:
        rows.append({'model': model, 'metric': metric, 'value': fmt(), 'test_set': test_set})
    except KeyError:
        pass

out = ROOT / 'web' / 'models' / 'metrics.json'
out.write_text(json.dumps({'source': 'results/deck_facts.txt (generated by the MATLAB evaluation scripts)',
                           'rows': rows}, indent=2), encoding='utf-8')
print(f'{len(rows)} rows -> {out}')
for r in rows:
    print(f"  {r['model']:28s} {r['metric']:55s} {r['value']}")
