function [mdlPath, out] = buildNetraSimulink(rates, doRun)
%BUILDNETRASIMULINK  Generate the Simulink district-screening model - D3.
%
%   [mdlPath, out] = buildNetraSimulink(RATES)        build only
%   [mdlPath, out] = buildNetraSimulink(RATES, true)  build and simulate
%
%   WHY PLAIN SIMULINK AND NOT SIMEVENTS.
%   SimEvents is licensed on this installation and ver() reports it, but the
%   product is not actually installed - there is no toolbox/simevents folder
%   and load_system('simevents') fails. Rather than claim a SimEvents model
%   that cannot be opened on this machine, the same queueing result is built
%   from core Simulink blocks, which are installed and verifiable.
%
%   THE MODEL. One state per arm: B, the ophthalmologist's backlog measured
%   in seconds of unread images. Daily recurrence, 250 working days:
%
%       B(k+1) = max( 0, B(k) + demand - capacity )
%
%   where demand is the reading time arriving that day and capacity is the
%   expert time available. Two arms run side by side on identical arrivals:
%
%       manual : every capture is read           -> demand > capacity
%       NETRA  : only flagged captures are read  -> demand < capacity
%
%   The point the model makes is not a percentage. It is that the manual arm
%   is an unstable system - its backlog grows without bound, so the queue is
%   not a staffing shortfall that overtime can absorb - while triage moves
%   the same programme to a stable one.
if nargin < 1 || isempty(rates)
    rates = struct('referable',0.20,'escalated',0.05,'rejected',0.05);
end
if nargin < 2, doRun = false; end
out = struct();

here  = fileparts(mfilename('fullpath'));
mdl   = 'netra_district';
mdlPath = fullfile(here, [mdl '.slx']);

if ~license('test','Simulink')
    error('NETRA:noSimulink','Simulink is not available in this installation.');
end

% ---- parameters, all derived from measured rates ------------------------
A.patientsPerYear   = 100000;
A.workingDays       = 250;
A.reviewSecManual   = 90;
A.reviewSecFlagged  = 75;
A.expertSecPerDay   = 6*3600;
arrivalsPerDay = A.patientsPerYear / A.workingDays;
% Same rule as districtSim: use a directly measured flagged fraction when the
% caller has one. The independence-assumed union overstated it by ~10 points.
if isfield(rates,'flaggedDirect') && ~isempty(rates.flaggedDirect)
    pFlagged = min(rates.flaggedDirect, 1);
else
    pFlagged = min(rates.referable + rates.escalated - rates.referable*rates.escalated, 1);
end
gradedPerDay = arrivalsPerDay * (1 - rates.rejected);
A.breakEvenFlagged = (A.expertSecPerDay / A.reviewSecFlagged) / arrivalsPerDay;

demandManual = arrivalsPerDay * A.reviewSecManual;
demandNetra  = gradedPerDay * pFlagged * A.reviewSecFlagged;

if bdIsLoaded(mdl), close_system(mdl, 0); end
if isfile(mdlPath), delete(mdlPath); end
new_system(mdl); load_system(mdl);

try
    buildArm(mdl, 'Manual',  demandManual, A.expertSecPerDay,  40);
    buildArm(mdl, 'NETRA',   demandNetra,  A.expertSecPerDay, 260);
catch ME
    close_system(mdl, 0);
    rethrow(ME);
end

add_block('built-in/Note', [mdl '/note'], 'Position',[40 470 40 470]);
set_param([mdl '/note'], 'Text', sprintf([ ...
    'NETRA district screening - ophthalmologist backlog (seconds of unread images)\n' ...
    'arrivals %.0f/day  |  flagged fraction %.3f  |  expert capacity %.0f s/day\n' ...
    'manual demand %.0f s/day   NETRA demand %.0f s/day\n' ...
    'generated by buildNetraSimulink from measured rates'], ...
    arrivalsPerDay, pFlagged, A.expertSecPerDay, demandManual, demandNetra));

set_param(mdl, 'SolverType','Fixed-step', 'Solver','FixedStepDiscrete', ...
               'FixedStep','1', 'StartTime','0', 'StopTime',num2str(A.workingDays));
save_system(mdl, mdlPath);
fprintf('wrote %s\n', mdlPath);
fprintf('arrivals %.0f/day | flagged %.1f%% | manual %.0f s/day vs capacity %.0f s/day\n', ...
        arrivalsPerDay, 100*pFlagged, demandManual, A.expertSecPerDay);

out.pFlagged      = pFlagged;
out.demandManual  = demandManual;
out.demandNetra   = demandNetra;
out.capacity      = A.expertSecPerDay;
out.arrivalsPerDay= arrivalsPerDay;
out.stableManual  = demandManual <= A.expertSecPerDay;
out.stableNetra   = demandNetra  <= A.expertSecPerDay;
out.breakEvenFlagged = A.breakEvenFlagged;

if doRun
    fprintf('simulating %d working days...\n', A.workingDays);
    try
        r = sim(mdl, 'StopTime', num2str(A.workingDays), 'SaveOutput','on');
        bm = squeeze(r.logsout.get('Manual_backlog').Values.Data);
        bn = squeeze(r.logsout.get('NETRA_backlog').Values.Data);
        out.backlogManual = bm(:);
        out.backlogNetra  = bn(:);
        out.finalManualDays = bm(end) / A.expertSecPerDay;
        out.finalNetraDays  = bn(end) / A.expertSecPerDay;
        fprintf('after %d days: manual backlog %.0f expert-days, NETRA %.0f expert-days\n', ...
                A.workingDays, out.finalManualDays, out.finalNetraDays);
        plotBacklog(out, A, here);
    catch ME
        fprintf('simulation did not complete: %s\n', ME.message);
    end
end
close_system(mdl, 1);
end

% =========================================================================
function buildArm(mdl, name, demand, capacity, y)
%BUILDARM  One backlog recurrence: B(k+1) = max(0, B(k) + demand - capacity).
p = @(x1,y1,x2,y2) [x1 y1 x2 y2];

add_block('simulink/Sources/Constant', [mdl '/' name '_demand'], ...
    'Position', p(40, y, 100, y+30), 'Value', num2str(demand));
add_block('simulink/Sources/Constant', [mdl '/' name '_capacity'], ...
    'Position', p(40, y+60, 100, y+90), 'Value', num2str(capacity));

add_block('simulink/Math Operations/Sum', [mdl '/' name '_sum'], ...
    'Position', p(160, y+15, 190, y+65), 'Inputs', '+-+', 'IconShape','rectangular');

add_block('simulink/Discontinuities/Saturation', [mdl '/' name '_floor'], ...
    'Position', p(230, y+20, 270, y+60), ...
    'UpperLimit','inf', 'LowerLimit','0');

add_block('simulink/Discrete/Unit Delay', [mdl '/' name '_backlog'], ...
    'Position', p(310, y+20, 350, y+60), 'InitialCondition','0');

add_block('simulink/Sinks/Scope', [mdl '/' name '_scope'], ...
    'Position', p(420, y+20, 460, y+60));

c = @(a,b) add_line(mdl, a, b, 'autorouting','on');
c([name '_demand/1'],   [name '_sum/1']);
c([name '_capacity/1'], [name '_sum/2']);
c([name '_sum/1'],      [name '_floor/1']);
c([name '_floor/1'],    [name '_backlog/1']);
c([name '_backlog/1'],  [name '_scope/1']);

% feedback: yesterday's backlog is the third addend
add_line(mdl, [name '_backlog/1'], [name '_sum/3'], 'autorouting','on');

% log the backlog signal under a stable name
ph = get_param([mdl '/' name '_backlog'], 'PortHandles');
set_param(ph.Outport(1), 'DataLogging', 'on', ...
    'DataLoggingNameMode','Custom', 'DataLoggingName', [name '_backlog']);
end

function plotBacklog(out, A, here)
figDir = fullfile(fileparts(fileparts(here)), 'figures');
if ~isfolder(figDir), mkdir(figDir); end
d = (0:numel(out.backlogManual)-1)';
f = lightFigure('Position',[100 100 720 420]);
plot(d, out.backlogManual/A.expertSecPerDay, '-', 'Color',[0.757 0.153 0.176], 'LineWidth',2.5); hold on;
plot(d, out.backlogNetra /A.expertSecPerDay, '-', 'Color',[0.243 0.557 0.353], 'LineWidth',2.5);
xlabel('working day'); ylabel('ophthalmologist backlog (expert-days of unread images)');
title('District screening backlog - 100,000 patients/year');
legend({'manual review of every image','NETRA edge triage'}, 'Location','northwest', 'Box','off');
grid on;
lightAxes(f);
exportgraphics(f, fullfile(figDir,'district_backlog.png'), 'Resolution',150);
close(f);
fprintf('wrote figures/district_backlog.png\n');
end
